name: CI - Tests y Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:11.1
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: protectora_test
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        ports:
          - 3307:3306

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias del backend
        run: npm install
        working-directory: backend

      - name: Esperar a que MariaDB esté lista
        run: |
          echo "Esperando a MariaDB..."
          for i in {1..30}; do
            mysqladmin ping -h 127.0.0.1 -P 3307 -u testuser -ptestpass && echo "¡MariaDB lista!" && exit 0
            sleep 2
          done
          echo "¡Timeout esperando MariaDB!" && exit 1

      - name: Crear base de datos y tablas
        run: |
          sudo apt-get update && sudo apt-get install -y mariadb-client
          mysql -h 127.0.0.1 -P 3307 -u testuser -ptestpass protectora_test < backend/init.sql

      - name: Ejecutar tests de integración
        run: npm run test:integration
        working-directory: backend
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3307
          DB_USER: testuser
          DB_PASSWORD: testpass
          DB_NAME: protectora_test
          PORT: 3001

  build_image:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Crear imagen Docker del backend
        run: docker build -t protectora-backend ./backend
